import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import { defineConfig } from "eslint/config";

export default defineConfig([
  {
    ignores: ["**/node_modules/**", "**/dist/**", "**/build/**"],
  },

  js.configs.recommended,

  // Server: Node.js, CommonJS
  {
    files: ["server/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: globals.node,
    },
  },

  // Client: React, browser, ES modules
  {
    files: ["client/**/*.{js,jsx}"],
    extends: [reactHooks.configs.flat.recommended, reactRefresh.configs.vite],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  },

  // Client build tooling runs in Node, not the browser
  {
    files: ["client/vite.config.js"],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Shared rules
  {
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      eqeqeq: ["error", "smart"],
      "prefer-const": "error",
      "no-var": "error",
    },
  },

  // shadcn/ui components are generated by its CLI and regenerated on update, so
  // they follow upstream's conventions rather than ours: a React namespace
  // import kept for types, and variant helpers exported alongside components.
  // Last, so it wins over the shared rules above. Everything else stays
  // linted, since these files are ours to edit.
  {
    files: ["client/src/components/ui/**/*.jsx"],
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^React$" }],
      "react-refresh/only-export-components": "off",
    },
  },
]);
