import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { defineConfig } from "eslint/config";

export default defineConfig([
  {
    ignores: ["**/node_modules/**", "**/dist/**", "**/build/**"],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  // Server: Node.js, ES modules
  {
    files: ["server/**/*.ts"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.node,
    },
  },

  // Client: React, browser, ES modules
  {
    files: ["client/**/*.{ts,tsx}"],
    extends: [reactHooks.configs.flat.recommended, reactRefresh.configs.vite],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
  },

  // Client build tooling runs in Node, not the browser
  {
    files: ["client/vite.config.ts"],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Shared rules
  {
    rules: {
      // The TypeScript-aware version, which understands type-only usage.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      eqeqeq: ["error", "smart"],
      "prefer-const": "error",
      "no-var": "error",
    },
  },

  // shadcn/ui components are generated by its CLI and regenerated on update, so
  // they follow upstream's conventions rather than ours: variant helpers are
  // exported alongside components. Everything else stays linted, since these
  // files are ours to edit.
  {
    files: ["client/src/components/ui/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
]);
